site_name: Oscleton SDK Documentation
site_description: Ableton Live companion SDK for Android

copyright: 'Copyright © 2018 Arthur Vimond'

theme: 
  name: 'material'
  language: en
  feature:
    tabs: true

extra:
  version: 0.1
  social:
    - type: 'globe'
      link: 'http://arthurvimond.fr'
    - type: 'github'
      link: 'https://github.com/arthurvimond'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/arthurvimond'

pages:
  - Introduction: index.md
  - Getting started:
    - Prerequesite: getting-started/prerequesite.md
    - Android project setup: getting-started/android-project-setup.md
    - Configuration: getting-started/configuration.md
    - Receiver: getting-started/receiver.md
  - API reference:
    - Package Index: api-reference/index.md
    - SDK:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk/index.md
      - OscletonSDK: api-reference/fr.arthurvimond.oscletonsdk/-oscleton-s-d-k/index.md
      - Configuration: api-reference/fr.arthurvimond.oscletonsdk/-configuration/index.md
      - Controller: api-reference/fr.arthurvimond.oscletonsdk/-controller/index.md
      - Receiver: api-reference/fr.arthurvimond.oscletonsdk/-receiver/index.md
      - ReactiveReceiver: api-reference/fr.arthurvimond.oscletonsdk/-reactive-receiver/index.md
      - CallbackReceiver: api-reference/fr.arthurvimond.oscletonsdk/-callback-receiver/index.md
    - Enums:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk.enums/index.md
#      - ClipState: api-reference/fr.arthurvimond.oscletonsdk.enums/-clip-state/index.md
      - TrackType: api-reference/fr.arthurvimond.oscletonsdk.enums/-track-type/index.md
    - Exceptions:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk.exceptions/index.md
      - OscletonSDKException: api-reference/fr.arthurvimond.oscletonsdk.exceptions/-oscleton-s-d-k-exception/index.md
    - Listeners:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk.listeners/index.md
      - OnTempoChangedListener: api-reference/fr.arthurvimond.oscletonsdk.listeners/-on-tempo-change-listener/index.md
#      - OnVolumeChangedListener: api-reference/fr.arthurvimond.oscletonsdk.listeners/-on-volume-change-listener/index.md
    - Models:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk.models/index.md
#      - Clip: api-reference/fr.arthurvimond.oscletonsdk.models/-clip/index.md
#      - ClipSlot: api-reference/fr.arthurvimond.oscletonsdk.models/-clip-slot/index.md
      - Device: api-reference/fr.arthurvimond.oscletonsdk.models/-device/index.md
      - DeviceParameter: api-reference/fr.arthurvimond.oscletonsdk.models/-device-parameter/index.md
#      - Scene: api-reference/fr.arthurvimond.oscletonsdk.models/-scene/index.md
      - Track: api-reference/fr.arthurvimond.oscletonsdk.models/-track/index.md
    - Utils:
      - Overview: api-reference/fr.arthurvimond.oscletonsdk.utils/index.md
      - Empty: api-reference/fr.arthurvimond.oscletonsdk.utils/-empty/index.md
#      - FormatUtils: api-reference/fr.arthurvimond.oscletonsdk.utils/-format-utils/index.md
#      - MathUtils: api-reference/fr.arthurvimond.oscletonsdk.utils/-math-utils/index.md
      - NetworkUtils: api-reference/fr.arthurvimond.oscletonsdk.utils/-network-utils/index.md
  - More:
    - Changelog: more/changelog.md
    - Feedback and issues: more/feedback-and-issues.md
    - License: more/license.md

markdown_extensions:
  - codehilite:
      linenums: false
  - markdown_fenced_code_tabs:
      single_block_as_tab: false
      active_class: 'active'
      template: 'default'


extra_javascript:
  - js/tabhack.js

extra_css:
  - 'css/general.css'
  - 'css/code-tabs.css'