site_name: Oscleton SDK Documentation
site_description: Ableton Live companion SDK for Android

copyright: 'Copyright © 2018 Arthur Vimond'

theme: 
  name: 'material'
  language: en
  feature:
    tabs: true

extra:
  version: 0.1
  social:
    - type: 'globe'
      link: 'http://arthurvimond.fr'
    - type: 'github'
      link: 'https://github.com/arthurvimond'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/arthurvimond'

nav:
  - Introduction: index.md
  - Getting started:
    - Prerequisite: getting-started/prerequisite.md
    - Android project setup: getting-started/android-project-setup.md
    - Configuration: getting-started/configuration.md
    - Controller: getting-started/controller.md
    - Receiver: getting-started/receiver.md
  - API reference:
    - Package Index: api-reference/index.md
    - SDK:
      - Overview: api-reference/com.oscleton.sdk/index.md
      - OscletonSDK: api-reference/com.oscleton.sdk/-oscleton-s-d-k/index.md
      - Configuration: api-reference/com.oscleton.sdk/-configuration/index.md
      - Controller: api-reference/com.oscleton.sdk/-controller/index.md
      - Receiver: api-reference/com.oscleton.sdk/-receiver/index.md
      - ReactiveReceiver: api-reference/com.oscleton.sdk/-reactive-receiver/index.md
      - CallbackReceiver: api-reference/com.oscleton.sdk/-callback-receiver/index.md
    - Enums:
      - Overview: api-reference/com.oscleton.sdk.enums/index.md
#      - ClipState: api-reference/com.oscleton.sdk.enums/-clip-state/index.md
      - TrackType: api-reference/com.oscleton.sdk.enums/-track-type/index.md
    - Exceptions:
      - Overview: api-reference/com.oscleton.sdk.exceptions/index.md
      - OscletonSDKException: api-reference/com.oscleton.sdk.exceptions/-oscleton-s-d-k-exception/index.md
    - Listeners:
      - Overview: api-reference/com.oscleton.sdk.listeners/index.md
      - OnConnectionSuccessListener: api-reference/com.oscleton.sdk.listeners/-on-connection-success-listener/index.md
      - OnDeviceParameterChangeListener: api-reference/com.oscleton.sdk.listeners/-on-device-parameter-change-listener/index.md
      - OnTempoChangeListener: api-reference/com.oscleton.sdk.listeners/-on-tempo-change-listener/index.md
    - Models:
      - Overview: api-reference/com.oscleton.sdk.models/index.md
#      - Clip: api-reference/com.oscleton.sdk.models/-clip/index.md
#      - ClipSlot: api-reference/com.oscleton.sdk.models/-clip-slot/index.md
      - Device: api-reference/com.oscleton.sdk.models/-device/index.md
      - DeviceParameter: api-reference/com.oscleton.sdk.models/-device-parameter/index.md
#      - Scene: api-reference/com.oscleton.sdk.models/-scene/index.md
      - Track: api-reference/com.oscleton.sdk.models/-track/index.md
    - Utils:
      - Overview: api-reference/com.oscleton.sdk.utils/index.md
      - Empty: api-reference/com.oscleton.sdk.utils/-empty/index.md
#      - FormatUtils: api-reference/com.oscleton.sdk.utils/-format-utils/index.md
#      - MathUtils: api-reference/com.oscleton.sdk.utils/-math-utils/index.md
      - NetworkUtils: api-reference/com.oscleton.sdk.utils/-network-utils/index.md
  - More:
    - Changelog: more/changelog.md
    - Feedback and issues: more/feedback-and-issues.md
    - License: more/license.md

markdown_extensions:
  - codehilite:
      linenums: false
  - markdown_fenced_code_tabs:
      single_block_as_tab: false
      active_class: 'active'
      template: 'default'


extra_javascript:
  - js/tabhack.js

extra_css:
#  - 'css/general.css'
  - 'css/code-tabs.css'